### ISSUE TITLE
FYI slight movement == funny results

### ISSUE THREAD

**Issue by zhuker** [posgraph/coupe.Video_stabilization_using_deep_learning_based_Optical_Flow#1]
i am working on stabilizing old film scans, so i ran across this project and decided to give it a try
film movement in scans i am working on is very subtle 
input video
http://kote.videogorillas.com/vmir/coupe.Video_stabilization_using_deep_learning_based_Optical_Flow/0.mp4
output result
http://kote.videogorillas.com/vmir/coupe.Video_stabilization_using_deep_learning_based_Optical_Flow/0_out.mp4

<img width="1680" alt="screen shot 2018-12-18 at 8 28 00 am" src="https://user-images.githubusercontent.com/4367682/50135974-df8a9380-029e-11e9-9e58-7e24ec8f1cf4.png">

**Comment by codeslake** [comment]
Hi, thank you for your comment.
First of all, I want to mention that this project is intermediate result of on-going research.

The problem on the stabilization result that you shared is one of our main concerns to solve.
Since the training dataset does not contain various kind of videos, stabilization process is not robust.
Also, the input video you shared is already stable, which the network has never seen during training time.
We are planning to publicize more robust network that can stabilize videos of various conditions, as well as stable video.

Since there is only sharing of your thought, I am closing this issue.
Thank you.
